### ISSUE TITLE
[son of sam] page flushes left on mobile

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/big-town#16]
After choosing a field in the drop down, the page flushes left cutting off the image and the text. I was on iPhone 6 plus on Safari.
![image uploaded from ios 1](https://user-images.githubusercontent.com/25779035/28944043-09eca28c-786f-11e7-9766-8cd30d09a08e.jpg)

**Comment by freejoe76** [comment]
Okay try it now, @ssmirti.
